### ISSUE TITLE
error at the infer screen step

### ISSUE THREAD

**Issue by rvweeren** [Joshuaalbert/bayes_gain_screens#16]
```
ref_image_fits -> /disks/paradata/shimwell/LoTSS-DR2/archive/P195+27/image_full_ampphase_di_m.NS.app.restored.fits
Traceback (most recent call last):
  File "/net/rijn/data2/rvweeren/screenstestDec2019/bayes_gain_screens/debug/scripts/infer_screen.py", line 99, in <module>
    main(**vars(flags))
  File "/net/rijn/data2/rvweeren/screenstestDec2019/bayes_gain_screens/debug/scripts/infer_screen.py", line 48, in main
    remake_posterior_solsets=True)
  File "/opt/miniconda3/envs/tf_py/lib/python3.6/site-packages/bayes_gain_screens-0.0.1-py3.6.egg/bayes_gain_screens/deploy.py", line 67, in __init__
    const, axes = datapack.const
  File "/opt/miniconda3/envs/tf_py/lib/python3.6/site-packages/bayes_gain_screens-0.0.1-py3.6.egg/bayes_gain_screens/datapack.py", line 600, in __getattr__
    selection = self.get_selection(soltab)
  File "/opt/miniconda3/envs/tf_py/lib/python3.6/site-packages/bayes_gain_screens-0.0.1-py3.6.egg/bayes_gain_screens/datapack.py", line 455, in get_selection
    raise ValueError('Soltab {} does not exist.'.format(soltab))
ValueError: Soltab const000 does not exist.

```

**Comment by Joshuaalbert** [comment]
Should be fixed with adeed59ac0e4bd0841b23b3ba4149f83a6c58c98
