### ISSUE TITLE
error related to updated flagging code(?)

### ISSUE THREAD

**Issue by rvweeren** [Joshuaalbert/bayes_gain_screens#26]
ref_image_fits -> /disks/paradata/shimwell/LoTSS-DR2/archive/P138+65/image_full_ampphase_di_m.NS.app.restored.fits
Traceback (most recent call last):
  File "/net/rijn/data2/rvweeren/screenstestDec2019/bayes_gain_screens/debug/scripts/infer_screen.py", line 99, in <module>
    main(**vars(flags))
  File "/net/rijn/data2/rvweeren/screenstestDec2019/bayes_gain_screens/debug/scripts/infer_screen.py", line 48, in main
    remake_posterior_solsets=True)
  File "/opt/miniconda3/envs/tf_py/lib/python3.6/site-packages/bayes_gain_screens-0.0.1-py3.6.egg/bayes_gain_screens/deploy.py", line 73, in __init__
    tec_uncert, _ = filter_tec_dir(tec[0,...], data_directions, init_y_uncert=tec_uncert[0,...], min_res=8., function='multiquadric')
  File "/opt/miniconda3/envs/tf_py/lib/python3.6/site-packages/bayes_gain_screens-0.0.1-py3.6.egg/bayes_gain_screens/outlier_detection.py", line 175, in filter_tec_dir
    reinout_flag = reinout_filter(directions[:,0], directions[:,1], y[:, a, t])
  File "/opt/miniconda3/envs/tf_py/lib/python3.6/site-packages/bayes_gain_screens-0.0.1-py3.6.egg/bayes_gain_screens/outlier_detection.py", line 111, in reinout_filter
    rbf_smooth = Rbf(racleaned, deccleaned, TECcleaned, smooth=0.3, function=rbftype)
  File "/opt/miniconda3/envs/tf_py/lib/python3.6/site-packages/scipy/interpolate/rbf.py", line 231, in __init__
    self.epsilon = np.power(np.prod(edges)/self.N, 1.0/edges.size)
ZeroDivisionError: float division by zero
Finisihed:
singularity exec -B /tmp,/dev/shm,$HOME,/disks/paradata,/data1,/net/lofar1,/net/rijn,/net/nederrijn/,/net/bovenrijn,/net/botlek,/net/para10,/net/lofar2,/net/lofar3,/net/lofar4,/net/lofar5,/net/lofar6,/net/lofar7,/disks/ftphome,/net/krommerijn,/net/voorrijn,/net/achterrijn,/home/rvweeren /net/rijn/data2/rvweeren/screenstestDec2019/singularity/bayes_gain_screens.simg \
python \
	/net/rijn/data2/rvweeren/screenstestDec2019/bayes_gain_screens/debug/scripts/infer_screen.py \
	--working_dir=/net/rijn/data2/rvweeren/screenstestDec2019/L626238/L626238/infer_screen \
	--obs_num=626238 \
	--data_dir=/net/rijn/data2/rvweeren/screenstestDec2019/L626238/L626238/download_archive \
	--ref_image_fits=/disks/paradata/shimwell/LoTSS-DR2/archive/P138+65/image_full_ampphase_di_m.NS.app.restored.fits \
	--block_size=20 \
	--max_N=250 \
	--ncpu=64 \
	--ref_dir=0 \
	--deployment_type=directional \
	2>&1 | tee -a infer_screen/state.log; exit ${PIPESTATUS[0]}
with exit code 1
Task infer_screen took 0.02 hours
FAILURE at: infer_screen

**Comment by Joshuaalbert** [comment]
Looks like the Rbf is trying to be calculated over just 1 point (so the number of edges is zero). Perhaps the progressive flagging is going too far for some reason?

**Comment by Joshuaalbert** [comment]
Note, that it's your outlier flagging code that is failing, not mine. It's here https://github.com/Joshuaalbert/bayes_gain_screens/blob/master/bayes_gain_screens/outlier_detection.py#L102

Do you see a reason the Rbf would be called on a single data point?

**Comment by Joshuaalbert** [comment]
Probably solved with 3f73d8193fce0f526da3bda9cedc1d2d302bb570
